imageUrl: https://raw.githubusercontent.com/adidas/adidas-yarn-design-system/master/logo.png
backgroundColor: '#f0cd66'
keywords:
  - adidas
  - design
  - design-system
  - yarn
  - css
  - less
  - bootstrap
  - bem
